// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY9_yeRalCv4VSfKOMEayQ_pWp3evR_c8',
    appId: '1:804658477538:web:7e278beb5f4781f93321bb',
    messagingSenderId: '804658477538',
    projectId: 'cobaajaa-8883b',
    authDomain: 'cobaajaa-8883b.firebaseapp.com',
    storageBucket: 'cobaajaa-8883b.appspot.com',
    measurementId: 'G-6PDVEHJCZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOwtqNQ_8Vow2WBFX7v80-hQVa2-xD1-g',
    appId: '1:804658477538:android:bf30bb2102cdbefe3321bb',
    messagingSenderId: '804658477538',
    projectId: 'cobaajaa-8883b',
    storageBucket: 'cobaajaa-8883b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRhjhS1pdjCu9nJrwAb0LBrGOyP0EXqsY',
    appId: '1:804658477538:ios:258b5f3fc9d426ed3321bb',
    messagingSenderId: '804658477538',
    projectId: 'cobaajaa-8883b',
    storageBucket: 'cobaajaa-8883b.appspot.com',
    iosBundleId: 'com.example.cobaaja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY9_yeRalCv4VSfKOMEayQ_pWp3evR_c8',
    appId: '1:804658477538:web:4891239ec43528753321bb',
    messagingSenderId: '804658477538',
    projectId: 'cobaajaa-8883b',
    authDomain: 'cobaajaa-8883b.firebaseapp.com',
    storageBucket: 'cobaajaa-8883b.appspot.com',
    measurementId: 'G-7HE0FNET0L',
  );
}
